# Licensed under the Apache-2.0 license

[vendor_fw_key_config]
ecc_pub_key = "vnd-pub-key-3.pem"
ecc_priv_key = "vnd-priv-key-3.pem"
lms_pub_key = "vnd-lms-pub-key-3.pem"
lms_priv_key = "vnd-lms-priv-key-3.pem"

[vendor_man_key_config]
ecc_pub_key = "vnd-pub-key-3.pem"
ecc_priv_key = "vnd-priv-key-3.pem"
lms_pub_key = "vnd-lms-pub-key-3.pem"
lms_priv_key = "vnd-lms-priv-key-3.pem"

[owner_fw_key_config]
ecc_pub_key = "own-pub-key.pem"
ecc_priv_key = "own-priv-key.pem"
lms_pub_key = "own-lms-pub-key.pem"
lms_priv_key = "own-lms-priv-key.pem"

[owner_man_key_config]
ecc_pub_key = "own-pub-key.pem"
ecc_priv_key = "own-priv-key.pem"
lms_pub_key = "own-lms-pub-key.pem"
lms_priv_key = "own-lms-priv-key.pem"

